export interface VersionEntry {
    version: string;
    date: string;
    description: string;
    changes: string[];
}

export const VERSION_HISTORY: VersionEntry[] = [
    {
        version: "2.6.0",
        date: "16/04/2026",
        description: "Nova aba Jornada do Lead — análise ponta-a-ponta do funil em 7 etapas com responsáveis, metas, comparação MoM justa e deep dive por etapa.",
        changes: [
            "Nova aba 'Jornada' entre Visão Geral e Funil, com 4 sub-views (Entrada e Agendamento, Reunião e Qualificação, Fechamento, Visão Completa).",
            "Motor puro lib/metrics-jornada.ts — 7 estágios (entrada → agendou → realizou → qualificou → agCloser → realizouCloser → vendeu), modos Coorte e Evento.",
            "Split passado/futuro para reuniões agendadas — show-up rate calcula sobre reuniões já passadas, não sobre total marcado (remove distorção causada por agendamentos futuros).",
            "Comparação Mês-a-Mês por subtração calendárica: 01-15 abril vs 01-15 março (não janelas deslizantes), preservando o dia do mês.",
            "MiniFunnel horizontal com 7 estágios, metas coloridas e PoP inline — dá leitura ponta-a-ponta em 3 segundos.",
            "StageChart: time-series por sub-view com picker de até 3 métricas, granularidade diária/semanal/mensal, tipos linha/barra/área e overlay tracejado do período anterior.",
            "StageDeepDive (modal): distribuição das respostas do lead (orçamento, convidados, destino, cidade, status do relacionamento, etc.) e decisões do SDR (qualificação, motivos de qualificação, desqualificação, perda), com taxa de preenchimento e tendência vs período anterior.",
            "ClosingBox por sub-view: prosa contínua, diagnóstico e sugestões de ação automáticas baseadas em gap vs meta e regressões.",
            "Toggle Narrada ⇆ Detalhada — mesma computação, apresentações diferentes para leitura executiva vs técnica.",
            "Análise de dropout entre cada par de etapas: quantos ficaram em aberto (por stage AC) e quantos foram perdidos (por motivo), com tendência PoP.",
            "DealsModal: linhas clicáveis abrem o deal direto no ActiveCampaign.",
            "WonDeal schema estendido com qualificado_para_sql, motivos_qualificacao_sdr, motivo_desqualificacao_sdr, motivo_de_perda, ww_closer_motivo_de_perda.",
            "28 novos testes Vitest para metrics-jornada (bucketing temporal, modos coorte/evento, past/future split, metas, targetRateBetween).",
        ],
    },
    {
        version: "2.5.0",
        date: "18/03/2026",
        description: "Filtro de período global, cache server-side, exportação CSV e correções críticas.",
        changes: [
            "Seletor de janela de dados no header: 30 dias, 90 dias, 180 dias, 1 ano, Tudo.",
            "Cache server-side /api/metrics com stale-while-revalidate por período (5min TTL, backoff 30s).",
            "Dashboard carrega de /api/metrics primeiro, fallback para queries diretas ao Supabase.",
            "Exportação CSV genérica (lib/export-csv.ts) com botão na aba Contratos.",
            "31 testes de componentes React (ErrorBoundary, KpiCard, SectionTitle, MonthSelector).",
            "Fix: DATE_COLS alinhado com campo 87 → data_fechamento.",
            "Fix: Auth do cron aceita x-vercel-cron header (Vercel cron não envia Bearer).",
            "Fix: backfill-deals.ts e mapping.json alinhados com campo 87.",
            "Fix: Slack webhook guard para string vazia + revalidation backoff.",
        ],
    },
    {
        version: "2.4.0",
        date: "18/03/2026",
        description: "Refatoração modular, otimizações de performance, testes automatizados e resiliência.",
        changes: [
            "PerfilScoreTab dividido em 7 sub-componentes React.memo (de 1864 para 323 linhas no orchestrator).",
            "metrics.ts: single-pass pré-classificação de closer deals — O(n) vs antigo O(6n).",
            "metrics-sdr.ts: weekMap/monthMap single-pass — O(n) vs antigo O(24n).",
            "lead-score.ts: 6 funções convertidas para single-pass (buildCloserMonthlyProfiles ~20x menos iterações).",
            "Pipeline helpers centralizados em funnel-utils.ts com Sets O(1) — eliminada duplicação 3x.",
            "ac-field-map.ts como fonte única de CONV_MAP/ORC_MAP/DESTINO_NORM (webhook importa de lá).",
            "Campo 87 alinhado para data_fechamento em todos os caminhos de ingestão.",
            "Promise.allSettled no Dashboard — falhas parciais exibem dados disponíveis.",
            "Error Boundaries por aba — crash isolado com fallback visual e retry.",
            "Widget de saúde do sync no header (🟢🟡🔴 baseado em idade e erros).",
            "Slack webhook na Edge Function sync-deals para alertas de falha.",
            "Trigger PostgreSQL deals_upsert_newer_only — resolve race condition webhook vs cron.",
            "192 testes automatizados (Vitest): 120 kpi-weddings + 72 dash-webhook.",
            "/api/sync protegido com SYNC_SECRET; CRON_SECRET obrigatório no deals/sync.",
            "Fetchers com maxPages=20 (safety limit) e erros propagados (não silenciados).",
            "Edge Function sync-deals: field lookup via Map O(1) (era O(n²)).",
            "deals-cleanup: single API call com ?include=dealCustomFieldData (era N+1).",
            "Ads spend: single query .or() em vez de 2 queries separadas.",
        ],
    },
    {
        version: "2.3.0",
        date: "17/03/2026",
        description: "Refactoring estrutural e otimizações de performance.",
        changes: [
            "Carregamento de dados paralelo via Promise.all (7 fontes simultâneas — antes sequencial).",
            "SELECT de ~44 colunas específicas em vez de SELECT * (redução de ~80% no payload de rede).",
            "Centralização do mapeamento row→WonDeal em função única (eliminação de 4 cópias duplicadas).",
            "Memoização de chatContext e allDeals no Dashboard (evita recálculo a cada render).",
            "Otimização de fetchStagesFromDb com limit (evita fetch de milhares de rows).",
            "Uso de .upsert() nativo do Supabase em upsertMonthlyTarget (1 query em vez de 2).",
            "Validação Zod na API de chat (limites de tamanho e tipos para messages e context).",
            "STATUS_MAP promovido a constante de módulo (evita recriação por row).",
            "Dedup simplificada em fetchAllFunnelDealsForMonth (1 Set em vez de 3).",
        ],
    },
    {
        version: "2.2.0",
        date: "13/03/2026",
        description: "Sync automático AC → Supabase via Edge Function e botão de sincronização manual.",
        changes: [
            "Supabase Edge Function 'sync-deals' para sync incremental AC → Supabase (janela de 3h).",
            "pg_cron agendado a cada 2h para disparar a Edge Function automaticamente.",
            "Botão 'Sync AC' no header do dashboard para sincronização manual sob demanda.",
            "Sync route simplificada: chama Edge Function via Supabase (zero env vars extras no Vercel).",
            "Auto-refresh do dashboard após sync bem-sucedido.",
        ],
    },
    {
        version: "2.1.0",
        date: "12/03/2026",
        description: "Chat IA, correção de webhook e auditoria de dados.",
        changes: [
            "Nova aba 'Chat IA' com assistente inteligente (GPT-4o) para perguntas em linguagem natural.",
            "Chat popup flutuante em todas as abas com contexto automático da tela atual.",
            "Histórico de chat persistido em localStorage.",
            "Correção crítica no webhook: mapeamento de campos por nome (key) em vez de ID numérico.",
            "Auditoria e correção de todos os 23.578 deals no banco — ~185 campos corrigidos.",
            "Correção do getCloserStatus: deals com data_fechamento agora são sempre classificados como Won.",
        ],
    },
    {
        version: "2.0.0",
        date: "09/03/2026",
        description: "Motor de Lead Scoring, abas Perfil & Score e Contratos.",
        changes: [
            "Novo motor de lead scoring simplificado baseado em destino, convidados e orçamento.",
            "Aba 'Perfil & Score' com Score Board, Potencial por Mês e Qualidade do Funil.",
            "Aba 'Contratos' com tabela detalhada de deals fechados e tooltip interativo.",
            "Configuração de bandas A/B/C persistida em localStorage.",
        ],
    },
    {
        version: "1.6.0",
        date: "06/03/2026",
        description: "Funil de Metas com separação Wedding/Elopement e integração Ads.",
        changes: [
            "Nova aba 'Funil Metas' com tabela completa de métricas do funil de vendas.",
            "Toggle de 3 visões: Wedding (apenas casamentos), Elopement (apenas elopements), Total (combinado).",
            "Separação completa de dados Wedding e Elopement em todas as métricas.",
            "Integração de dados de Meta Ads e Google Ads com cards de spend, clicks e CPM (em progresso).",
            "Cálculo automático de CPL baseado no investimento total e leads gerados.",
            "Cards de taxas de conversão (CVR) entre cada etapa do funil.",
            "Comparação com período anterior e metas planejadas.",
            "Modal de drill-down para visualizar deals de cada etapa.",
            "Nova logo Welcome Weddings no header do dashboard.",
        ],
    },
    {
        version: "1.5.0",
        date: "02/03/2026",
        description: "Refinamento SDR: Funil Semanal e métricas sincronizadas.",
        changes: [
            "Funil SDR agora exibe a última semana completa por padrão.",
            "Sincronização total entre cards de KPI e baldes do gráfico (início no domingo).",
            "Incorporação de novos campos: Fonte do Lead, Qualificação SQL e Status de Taxa.",
            "Anotação de picos históricos (Ago/24 e Jan/25) no gráfico de taxa de serviço.",
            "Aumento da janela histórica de deals SDR para 180 dias.",
        ],
    },
    {
        version: "1.4.0",
        date: "27/02/2026",
        description: "Correção da Lógica de Casamentos Ganhos e Pipeline Closer.",
        changes: [
            "Alteração do ID do pipeline Closer de 8 para 3.",
            "Correção da inversão de status (Ganho vs Aberto) no script de sincronização.",
            "Implementação da regra global de identificação de ganho via campo '[WW] [Closer] Data-Hora Ganho'.",
            "Mapeamento direto do campo customizado 87 para persistência de data de fechamento.",
            "Recarga total de 22.000+ deals para garantir integridade histórica.",
        ],
    },
    {
        version: "1.3.0",
        date: "27/02/2026",
        description: "Revamp estrutural Aba SDR (Topo do Funil).",
        changes: [
            "Renomeação oficial da tab para 'SDR'.",
            "Módulo 2.1: Cards de KPI otimizados com MM4 visível, no-show rate e qualificação com ruleset de alertas.",
            "Módulo 2.2: Novo gráfico Híbrido exibindo Leads vs Engajados + Curva de Qualificação.",
            "Módulo 2.3: Funil visual de 5 etapas com lógica estrita de pass-through.",
            "Módulo 2.4: Painéis duplo de Motivos de Perda (Global vs Últimos 4 Meses com detecção de tendências).",
            "Módulo 2.5: Acompanhamento mensal isolado de rejeição por Taxa de Serviço.",
        ],
    },
    {
        version: "1.2.0",
        date: "26/02/2026",
        description: "Dicionário de Métricas e Auxiliares Visuais.",
        changes: [
            "Criação da página 'Dicionário' com definições detalhadas de cada métrica.",
            "Implementação de hover helpers (tooltips) em todos os KPIs e títulos de seção.",
            "Centralização das regras de cálculo e origens de dados em `metrics-definitions.ts`.",
            "Melhoria na transparência dos dados para os usuários finais.",
        ],
    },
    {
        version: "1.1.0",
        date: "25/02/2026",
        description: "Migração de infraestrutura de dados e sistema de versionamento.",
        changes: [
            "Migração da origem de dados: API do ActiveCampaign -> Supabase Database.",
            "Eliminação de problemas de CORS e dependência de proxy server-side.",
            "Implementação de sistema de versionamento e log de alterações (este log).",
            "Mapeamento automático de campos personalizados do DB para o dashboard.",
            "Melhoria na performance de carregamento inicial.",
        ],
    },
    {
        version: "1.0.0",
        date: "19/02/2026",
        description: "Lançamento inicial do Dashboard de Vendas Welcome Weddings.",
        changes: [
            "Visualização de KPIs (SDR Volume, Taxa de Qualificação, Conversão Closer).",
            "Gráficos de tendência semanal e mensal (Area e Bar charts).",
            "Análise de motivos de perda e pipeline por idade/estágio.",
            "Tema escuro personalizado (Berry/Gold/Surface).",
            "Consumo direto da API ActiveCampaign via Proxy Next.js.",
        ],
    },
];

export const CURRENT_VERSION = VERSION_HISTORY[0];
