export interface VersionEntry {
    version: string;
    date: string;
    description: string;
    changes: string[];
}

export const VERSION_HISTORY: VersionEntry[] = [
    {
        version: "2.9.1",
        date: "07/05/2026",
        description: "Nova aba Board Mensal (KPI × mês com toggle Coorte/Evento e janela configurável) + regra canônica isClosedWwContract corrigindo subestimação de ~67% em contratos (deals migram para pós-venda após fechar).",
        changes: [
            "Nova aba Board Mensal — tabela KPI × mês com 11 linhas (Invest, Leads, MQL, Qualif SDR, Reun Closer, Contratos, CAC, Conv Lead→MQL, Conv SDR→Closer, Close Rate, Win Rate). Toggle modo Evento/Coorte (default Evento, espelho SDR/Closer). Janela configurável: 3m/6m/12m/Ano corrente (default 6m + atual). Mês corrente com meta prorrateada (× dias decorridos / dias do mês).",
            "Toggle Coorte/Evento: Evento conta pelo timestamp do evento próprio; Coorte ancora pela `created_at` no mês e mostra o que aconteceu com essa coorte. Em Coorte as taxas são reais (subset); em Evento são informativas. Banner amarelo avisa que coortes recentes têm leads ainda no funil.",
            "Conv SDR → Closer recalibrada: era `reuniões realizadas / qualif`; agora `contratos / qualif` — sinaliza qualidade da qualificação do SDR (% do que ele aprovou virou venda).",
            "Linha Leads (6 pipelines + Elopment via isInWwLeadsPipeline) adicionada acima de MQL.",
            "Nova regra canônica `isClosedWwContract` em lib/funnel-utils.ts: 3 sinais cumulativos — data_fechamento + pipeline na whitelist WW (11 pipelines incluindo pós-venda Convidados/Convidados - Michelly/WW - Gestão Casamento/WW - Gestão Convidados/Produção) + sinal de funil (data_qualificado OR data_horario_agendamento_closer).",
            "Bug fix histórico: dashboard mostrava 4 contratos em mai/2025 quando o real era 13 (12 WW + 1 Trips). Causa: filtro só por MQL pipeline perdia os 8 deals que tinham migrado para pós-venda após fechar. Validação 19 meses: ~150 contratos totais, ~141 WW corrigidos.",
            "Helpers retroativos `isWwLeadHistoric` e `isWwMqlHistoric` incluem pipelines de pós-venda quando há sinal de funil, evitando subestimação de Lead/MQL/Qualif/Reun em meses antigos.",
            "Aplicação consistente: motor Board Mensal, motor Closer (Contrato + Cohort de Fechamento), FunnelMetaTab (campo vendas) agora usam `isClosedWwContract`. SDR não tem KPI de contratos diretamente.",
            "Memória de projeto `project_ww_contract_definition.md` documenta a regra completa + onde aplica. Tooltip `STAGE_DEFINITION` por KPI no Board Mensal explica modo Evento/Coorte e fórmulas. JSDoc denso em funnel-utils.ts.",
            "Pendência sinalizada: endpoint `/api/board/weekly` (Cowork) em lib/board/funnel-ww.ts usa filtro antigo (LEADS_PIPELINES = 5 sem Elopment, sem pós-venda). Subestima contratos também. Sprint dedicado para alinhar.",
            "2 testes novos em metrics-closer.test.ts (contrato em pipeline pós-venda + rejeição sem sinal de funil) + 6 fixtures ajustadas. Suite 323/328 verdes (5 falhas pré-existentes MonthSelector mantidas).",
        ],
    },
    {
        version: "2.9.0",
        date: "06/05/2026",
        description: "Redesign da aba Closer (continuação do funil SDR) — funil de 3 etapas (Reunião Agendada → Reunião Realizada → Contrato), CAC + CPL + Tempo até Fechamento, Cohort de Fechamento substituindo MM4s legacy, motivos de perda preservados. Mesmo padrão visual da SDR (modo calendário, Coorte/Evento, tooltips por etapa).",
        changes: [
            "Funil de 3 etapas no hero — cada card mostra valor + meta prorrateada (closer_agendada, closer_realizada, vendas). Click abre DealsModal com lista filtrada. Chevrons entre cards mostram taxa Realizada/Agendada (comparecimento) e Contrato/Realizada (close rate). Linha derivada exibe Conv. MQL→Contrato.",
            "CAC = (spend Meta + Google) ÷ contratos fechados — sem meta no monthly_targets nesta versão. CPL replicado da SDR (idem), permite ler eficiência do funil completo. Custo por contrato é o KPI mais importante para growth.",
            "Tempo até Fechamento = média de dias entre created_at do lead e data_fechamento, calculada apenas dos contratos fechados no período (n exibido para janelas curtas). Substitui o tempoMedioFechamento do metrics-contracts com escopo restrito.",
            "Cohort de Fechamento substitui o cohort 14-28d/29-45d legacy. Para coorte de leads criados no período: ✓ Fecharam (data_fechamento ≠ null), … Em aberto (status ≠ Lost), ✗ Perderam (status = Lost). Barra empilhada + 3 contadores clicáveis. Para 'Este mês' com modo calendário, compara % fechado da coorte atual vs coorte do mês anterior no mesmo dia-do-mês — leitura de velocidade.",
            "Modo Coorte/Evento espelha SDR/Jornada. Persistido em localStorage('ww-closer-mode'). Modo calendário ('Este mês' estende até endOfMonth) reusa resolvePeriodForSdr — agendamentos e contratos futuros já marcados entram.",
            "Top motivos de perda preservados em horizontal BarChart (top 8). Conta apenas deals MQL com status='2' (Lost) AND data_fechamento NULL no período. Função aggregateLossReasons exportada de lib/metrics-closer.ts.",
            "lib/metrics-closer.ts: novo motor puro análogo a metrics-sdr.ts. Tipos: CloserFunnelDetailed, CloserRates, CloserCostBlock, CloserCohort, CloserMissingData. Reusa isInWwLeadsPipeline, isInWwMqlPipeline, realizouCloser. 17 testes cobrem funil/coorte/CAC/CPL/cohort/lossReasons/missingData.",
            "components/dashboard/CloserTab.tsx: reescrita completa. Removidos os 4 KPIs MM4s, BarChart de janelas 4-semanas, cohort 14-28d/29-45d, análise por destino, breakdown período atual stacked. Componentes locais (FunnelKpiCard, FunnelChevron, CostCard, TimeCard, CohortFechamentoCard, ModeToggle, MissingDataBanner) replicados inline do padrão SDRTab — Phase 2 pode extrair para shared/.",
            "Banner de alertas no topo da aba (closer_agendada/closer_realizada/vendas sem meta, spend parcial, sync atrasada >6h). MissingDataBanner reusa visual do SDR.",
            "STAGE_DEFINITION: tooltip nativo (hover) por card do funil com a definição precisa do que conta. Mesmo padrão da SDR — analistas precisam confiar no número.",
            "Direção visual: ultra-modern, calm, tactile. Hierarquia tipográfica forte (números fontWeight 200), padding generoso, hover com translateY(-2px) + sombra, transitions 200ms ease, paleta calma. Verde/âmbar/vermelho apenas em badges pequenos.",
        ],
    },
    {
        version: "2.8.1",
        date: "06/05/2026",
        description: "Iteração na aba SDR — modo calendário para 'Este mês' (incluindo agendamentos futuros), Lead inclui Elopment (alinhado com Funil do Mês), tooltips por etapa e contagem do funil completa.",
        changes: [
            "Bug crítico corrigido: dashboard mostrava AG. CLOSER = 0 quando claramente havia reuniões agendadas no mês. Causa dupla: fetchAllDealsFromDb filtrava por created_at no período (deals criados antes ficavam de fora), e end=hoje excluía agendamentos no futuro.",
            "Nova fn resolvePeriodForSdr em lib/period-selection.ts: para preset 'Este mês' estende end até endOfMonth (modo calendário), incluindo agendamentos já marcados para o futuro. Demais presets inalterados. Retorna daysElapsedInPeriod para o motor prorratear meta pelo ritmo decorrido (não pelo mês inteiro).",
            "Fetch dos pipelines WW para o SDR usa janela estendida: start − 90 dias (buffer pra trás) até endOfMonth. Sem isso, deals criados em meses anteriores com data_closer/data_reuniao_1 no período corrente sumiam.",
            "Lead = aquisição bruta agora inclui Elopment Wedding (6 pipelines). MQL continua restrito a SDR + Closer + Planejamento (3 pipelines). Diferença bate com aba Funil do Mês: Lead − MQL = Internacional + Desqualificados + Elopment. Decisão alinhada com convenção de growth marketing.",
            "Novo grupo 12 (Elopment Wedding) registrado em GROUP_TO_PIPELINE e adicionado ao fetch SDR no Dashboard.tsx. Sem isso, expandir o escopo Lead não tinha efeito (deals nem chegavam ao motor).",
            "Lead/MQL agora são contados a partir dos 5+1 grupos WW (1, 3, 4, 12, 17, 31) deduplicados, não só dos pipelines do SDR/Closer. Pipelines 4, 17 e 31 estavam fora do fetch original — Lead/MQL apareciam idênticos em produção.",
            "STAGE_DEFINITION em SDRTab.tsx: tooltip nativo (hover) em cada card do funil com a definição precisa de Lead, MQL, Agendamento, Reunião, Qualificação e Ag. Closer. Sincronizado com isInLeadScope/isInMqlScope.",
            "Subtitle do header SDR ganhou glossário inline: 'lead (entrada bruta, inclui Elopment) → MQL (SDR + Closer + Planejamento) → ...'.",
            "Tooltip (i) ao lado de 'Este mês' explica o modo calendário quando ativo.",
            "Removido card 'vs período anterior' de todas as etapas — pipeline é vivo (leads mudam de estágio), comparação não é justa. Cards mostram apenas atingimento de meta.",
            "Custo por Lead (CPL) e Custo por MQL agora são cards separados. CPL tem meta de monthly_targets.cpl; cpMql não tem meta (informativo).",
            "Filtro de title 'EW%' removido do escopo Lead — leads bonafide podem usar esse prefixo (decisão Marketing).",
            "Documentação: project_sdr_funnel_definition.md em memory; JSDoc denso em isInLeadScope/isInMqlScope; comentário sobre fetch ampliado em Dashboard.tsx. Validado contra Supabase em abril/2026: Lead = 340, MQL = 247.",
        ],
    },
    {
        version: "2.8.0",
        date: "06/05/2026",
        description: "Redesign completo da aba SDR como dashboard de growth marketing — funil de 6 etapas (Lead → MQL → Agendamento → Reunião → Qualificação → Closer) com comparação tripla (atual × meta prorrateada × período anterior), bloco de investimento + CPL, modo Coorte/Evento e DealsModal por etapa.",
        changes: [
            "Novo funil de 6 etapas em hero scannable, cada card mostra valor grande + delta vs período anterior + barra de atingimento de meta. Click em qualquer card abre o DealsModal com a lista filtrada de deals daquela etapa.",
            "Lead = todo deal criado em pipelines WW (5 pipelines, exclui elopement e títulos EW%); MQL = subset que entrou em pipelines SDR válidos (exclui Internacional/Desqualificados). A taxa Lead→MQL no chevron sinaliza eficácia do filtro de pré-qualificação.",
            "Toggle Coorte/Evento (espelha o padrão da Jornada). Coorte: leads criados no período + onde estão hoje. Evento: o que aconteceu no período (default). Persistido em localStorage.",
            "Comparação contra meta: monthly_targets prorrateado linearmente (target_periodo = monthly × dias_periodo / dias_no_mes_de_end). CPL target NÃO prorrateia (é taxa).",
            "Comparação contra período anterior: mesma duração imediatamente antes (ex: 'Últimos 7 dias' vs '7 dias antes disso').",
            "Custo por MQL (CPL) = (spend Meta + Google) ÷ MQL no período. Card dedicado com meta cpl + delta vs ant. Cor invertida (verde = abaixo da meta).",
            "Investimento mídia: total + breakdown Meta/Google + delta vs período anterior + meta prorrateada (target_total = cpl × mql_target).",
            "Banner de alertas no topo da aba lista campos sem meta no monthly_targets, spend parcial em ads_daily_cache, sync com AC atrasada (>6h).",
            "Investigation Panel preservado (decomposição volume × taxa, breakdown por SDR, motivos de variação) — abre dentro da aba abaixo do funil.",
            "Removidos: Daily Trend Chart com drill-down, DOW Heatmap, Motivos cards (≈ 350 linhas de UI legacy). Os shapes legacy de SDRMetrics permanecem para back-compat dos 24 testes legados.",
            "lib/metrics-sdr.ts: novo tipo `SDRFunnelDetailed` com `{current, previous, target, deals}` por etapa, `SDRSpendBlock`, `SDRCplBlock`, `SDRMissingData`. Função aceita `options: { mode, targets, spend, previousSpend, daysInTargetMonth, staleSync, spendPartial }`.",
            "lib/supabase-api.ts: novo `fetchAdsSpendByRange(start, end)` agrega ads_daily_cache atravessando fronteiras de mês e detecta gap (partial=true).",
            "components/Dashboard.tsx: useEffect dispara fetch paralelo de monthly_targets + spend (atual e período anterior) ao mudar periodSelection. Passa props para SDRTab.",
            "Direção visual: Ultra-modern, calm, tactile — typography hierárquica (números fontWeight 200), padding generoso, hover com translateY(-2px) + sombra, transitions 200ms ease, paleta calma (T.gold reservado para hero metrics).",
            "Acessibilidade: cards do funil são <button> (Enter/Space ativa), aria-pressed no ModeToggle, banner com role='status'.",
            "26 testes novos em lib/__tests__/metrics-sdr-v2.test.ts cobrindo Lead/MQL filter, modos coorte/evento (inclusive divergência em Agendamento), prorrateio de target, CPL, missingData. 24 testes legados continuam passando.",
        ],
    },
    {
        version: "2.7.0",
        date: "04/05/2026",
        description: "Endpoint /api/board/weekly v1 — fonte de verdade do funil para Cowork (Board Executivo automatizado), com paridade WW + WT e correção da detecção de reunião closer no dashboard.",
        changes: [
            "Novo endpoint GET /api/board/weekly?brand=ww|wt&start=YYYY-MM-DD&end=YYYY-MM-DD com 4 janelas (weekly, mtd, rolling_30d, previous_4w_avg), targets, data_freshness e kpi_definitions_hash. Auth via Bearer (BOARD_API_KEY) constant-time. Ver docs/board-api-briefing.md (v1.2).",
            "lib/board/* (12 módulos): types, constants, period (BRT↔UTC via date-fns-tz), auth, deals-fetcher, funnel-ww, funnel-wt, data-freshness, targets, audit, rate-limit (Vercel KV + fallback in-memory), orchestrator, supabase-admin. 58 testes Vitest dedicados.",
            "Fix do dashboard: detecção de 'reunião closer realizada' migrada da coluna legacy reuniao_closer (dead column, sem FIELD_MAP entry) para os campos vivos AC ww_como_foi_feita_reuni_o_closer (id 299) e tipo_da_reuni_o_com_a_closer (id 19). Aplica em metrics.ts, metrics-jornada.ts e funnel-utils.ts. Números de reuniões realizadas no dashboard agora batem com a verdade do AC (estavam silenciosamente 0/zero há semanas).",
            "Field map AC: novo campo 332 'SDR WT - Data Fechamento Taxa' → coluna sdr_wt_data_fechamento_taxa. Adicionado em FIELD_MAP, FIELD_KEY_MAP e DATE_COLS no _shared/field-maps.ts do dash-webhook. Usado pelo board para computar funnel.weekly.vendas (WT).",
            "Migration aplicada (dash-webhook/supabase/migrations/20260430_board_endpoint.sql): coluna sdr_wt_data_fechamento_taxa em deals, 5 índices em data_qualificado/data_closer/data_fechamento/sdr_wt_data_fechamento_taxa/(pipeline,created_at), tabela board_audit_log com RLS service-role-only e cleanup pg_cron mensal (12 meses retenção).",
            "Edge Functions sync-deals e activecampaign-webhook re-deployadas via supabase CLI com _shared/field-maps.ts atualizado.",
            "WonDeal schema estendido: pagamento_de_taxa, pagou_a_taxa, sdr_wt_data_fechamento_taxa, created_at, data_closer (todos opcionais).",
            "Novas dependências: date-fns-tz (timezone correto BRT/UTC), @vercel/kv (rate limit; opcional, fallback in-memory funcional para dev).",
            "Documentação: docs/board-api-briefing.md (v1.2, contrato canônico), docs/cowork-instructions.md (system prompt do consumer Claude Cowork), docs/cowork-kickoff-prompt.md (mensagem inicial do dry-run).",
        ],
    },
    {
        version: "2.6.1",
        date: "16/04/2026",
        description: "Iterações no Deep Dive da Jornada: recuperação de valores legados de orçamento, novos campos e limpeza de blocos sem contexto.",
        changes: [
            "Safety net para orçamento em mapRowToWonDeal: valores legados >= R$ 1M e múltiplos de 100 são divididos por 100 na leitura — corrige valores antigos armazenados com formatação BR removida ('R$ 50.000,00' → '5000000' no banco).",
            "Deep Dive: novos campos na seção 'Respostas do lead' (como_conheceu_a_ww) e 'Registro do SDR' (como_foi_feita_a_1a_reuniao, tipo_reuniao_closer).",
            "Deep Dive: blocos sem contexto (nenhum deal respondeu no período atual nem no anterior) são escondidos automaticamente. Grupos inteiros vazios também somem — nada de 'Sem respostas neste período' repetido.",
            "Novo campo como_conheceu_a_ww exposto em WonDeal schema, DEAL_COLUMNS e mapRowToWonDeal.",
            "dash-webhook: parseNumber corrigido para entender formato BR ('R$ 50.000,00' → 50000, '1.500.000' → 1500000) em _shared/field-maps.ts, scripts/backfill-deals.mjs e scripts/reprocess-raw-data.mjs. ⚠️ Deploy pendente — estado local não commitado.",
        ],
    },
    {
        version: "2.6.0",
        date: "16/04/2026",
        description: "Nova aba Jornada do Lead — análise ponta-a-ponta do funil em 7 etapas com responsáveis, metas, comparação MoM justa e deep dive por etapa.",
        changes: [
            "Nova aba 'Jornada' entre Visão Geral e Funil, com 4 sub-views (Entrada e Agendamento, Reunião e Qualificação, Fechamento, Visão Completa).",
            "Motor puro lib/metrics-jornada.ts — 7 estágios (entrada → agendou → realizou → qualificou → agCloser → realizouCloser → vendeu), modos Coorte e Evento.",
            "Split passado/futuro para reuniões agendadas — show-up rate calcula sobre reuniões já passadas, não sobre total marcado (remove distorção causada por agendamentos futuros).",
            "Comparação Mês-a-Mês por subtração calendárica: 01-15 abril vs 01-15 março (não janelas deslizantes), preservando o dia do mês.",
            "MiniFunnel horizontal com 7 estágios, metas coloridas e PoP inline — dá leitura ponta-a-ponta em 3 segundos.",
            "StageChart: time-series por sub-view com picker de até 3 métricas, granularidade diária/semanal/mensal, tipos linha/barra/área e overlay tracejado do período anterior.",
            "StageDeepDive (modal): distribuição das respostas do lead (orçamento, convidados, destino, cidade, status do relacionamento, etc.) e decisões do SDR (qualificação, motivos de qualificação, desqualificação, perda), com taxa de preenchimento e tendência vs período anterior.",
            "ClosingBox por sub-view: prosa contínua, diagnóstico e sugestões de ação automáticas baseadas em gap vs meta e regressões.",
            "Toggle Narrada ⇆ Detalhada — mesma computação, apresentações diferentes para leitura executiva vs técnica.",
            "Análise de dropout entre cada par de etapas: quantos ficaram em aberto (por stage AC) e quantos foram perdidos (por motivo), com tendência PoP.",
            "DealsModal: linhas clicáveis abrem o deal direto no ActiveCampaign.",
            "WonDeal schema estendido com qualificado_para_sql, motivos_qualificacao_sdr, motivo_desqualificacao_sdr, motivo_de_perda, ww_closer_motivo_de_perda.",
            "28 novos testes Vitest para metrics-jornada (bucketing temporal, modos coorte/evento, past/future split, metas, targetRateBetween).",
        ],
    },
    {
        version: "2.5.0",
        date: "18/03/2026",
        description: "Filtro de período global, cache server-side, exportação CSV e correções críticas.",
        changes: [
            "Seletor de janela de dados no header: 30 dias, 90 dias, 180 dias, 1 ano, Tudo.",
            "Cache server-side /api/metrics com stale-while-revalidate por período (5min TTL, backoff 30s).",
            "Dashboard carrega de /api/metrics primeiro, fallback para queries diretas ao Supabase.",
            "Exportação CSV genérica (lib/export-csv.ts) com botão na aba Contratos.",
            "31 testes de componentes React (ErrorBoundary, KpiCard, SectionTitle, MonthSelector).",
            "Fix: DATE_COLS alinhado com campo 87 → data_fechamento.",
            "Fix: Auth do cron aceita x-vercel-cron header (Vercel cron não envia Bearer).",
            "Fix: backfill-deals.ts e mapping.json alinhados com campo 87.",
            "Fix: Slack webhook guard para string vazia + revalidation backoff.",
        ],
    },
    {
        version: "2.4.0",
        date: "18/03/2026",
        description: "Refatoração modular, otimizações de performance, testes automatizados e resiliência.",
        changes: [
            "PerfilScoreTab dividido em 7 sub-componentes React.memo (de 1864 para 323 linhas no orchestrator).",
            "metrics.ts: single-pass pré-classificação de closer deals — O(n) vs antigo O(6n).",
            "metrics-sdr.ts: weekMap/monthMap single-pass — O(n) vs antigo O(24n).",
            "lead-score.ts: 6 funções convertidas para single-pass (buildCloserMonthlyProfiles ~20x menos iterações).",
            "Pipeline helpers centralizados em funnel-utils.ts com Sets O(1) — eliminada duplicação 3x.",
            "ac-field-map.ts como fonte única de CONV_MAP/ORC_MAP/DESTINO_NORM (webhook importa de lá).",
            "Campo 87 alinhado para data_fechamento em todos os caminhos de ingestão.",
            "Promise.allSettled no Dashboard — falhas parciais exibem dados disponíveis.",
            "Error Boundaries por aba — crash isolado com fallback visual e retry.",
            "Widget de saúde do sync no header (🟢🟡🔴 baseado em idade e erros).",
            "Slack webhook na Edge Function sync-deals para alertas de falha.",
            "Trigger PostgreSQL deals_upsert_newer_only — resolve race condition webhook vs cron.",
            "192 testes automatizados (Vitest): 120 kpi-weddings + 72 dash-webhook.",
            "/api/sync protegido com SYNC_SECRET; CRON_SECRET obrigatório no deals/sync.",
            "Fetchers com maxPages=20 (safety limit) e erros propagados (não silenciados).",
            "Edge Function sync-deals: field lookup via Map O(1) (era O(n²)).",
            "deals-cleanup: single API call com ?include=dealCustomFieldData (era N+1).",
            "Ads spend: single query .or() em vez de 2 queries separadas.",
        ],
    },
    {
        version: "2.3.0",
        date: "17/03/2026",
        description: "Refactoring estrutural e otimizações de performance.",
        changes: [
            "Carregamento de dados paralelo via Promise.all (7 fontes simultâneas — antes sequencial).",
            "SELECT de ~44 colunas específicas em vez de SELECT * (redução de ~80% no payload de rede).",
            "Centralização do mapeamento row→WonDeal em função única (eliminação de 4 cópias duplicadas).",
            "Memoização de chatContext e allDeals no Dashboard (evita recálculo a cada render).",
            "Otimização de fetchStagesFromDb com limit (evita fetch de milhares de rows).",
            "Uso de .upsert() nativo do Supabase em upsertMonthlyTarget (1 query em vez de 2).",
            "Validação Zod na API de chat (limites de tamanho e tipos para messages e context).",
            "STATUS_MAP promovido a constante de módulo (evita recriação por row).",
            "Dedup simplificada em fetchAllFunnelDealsForMonth (1 Set em vez de 3).",
        ],
    },
    {
        version: "2.2.0",
        date: "13/03/2026",
        description: "Sync automático AC → Supabase via Edge Function e botão de sincronização manual.",
        changes: [
            "Supabase Edge Function 'sync-deals' para sync incremental AC → Supabase (janela de 3h).",
            "pg_cron agendado a cada 2h para disparar a Edge Function automaticamente.",
            "Botão 'Sync AC' no header do dashboard para sincronização manual sob demanda.",
            "Sync route simplificada: chama Edge Function via Supabase (zero env vars extras no Vercel).",
            "Auto-refresh do dashboard após sync bem-sucedido.",
        ],
    },
    {
        version: "2.1.0",
        date: "12/03/2026",
        description: "Chat IA, correção de webhook e auditoria de dados.",
        changes: [
            "Nova aba 'Chat IA' com assistente inteligente (GPT-4o) para perguntas em linguagem natural.",
            "Chat popup flutuante em todas as abas com contexto automático da tela atual.",
            "Histórico de chat persistido em localStorage.",
            "Correção crítica no webhook: mapeamento de campos por nome (key) em vez de ID numérico.",
            "Auditoria e correção de todos os 23.578 deals no banco — ~185 campos corrigidos.",
            "Correção do getCloserStatus: deals com data_fechamento agora são sempre classificados como Won.",
        ],
    },
    {
        version: "2.0.0",
        date: "09/03/2026",
        description: "Motor de Lead Scoring, abas Perfil & Score e Contratos.",
        changes: [
            "Novo motor de lead scoring simplificado baseado em destino, convidados e orçamento.",
            "Aba 'Perfil & Score' com Score Board, Potencial por Mês e Qualidade do Funil.",
            "Aba 'Contratos' com tabela detalhada de deals fechados e tooltip interativo.",
            "Configuração de bandas A/B/C persistida em localStorage.",
        ],
    },
    {
        version: "1.6.0",
        date: "06/03/2026",
        description: "Funil de Metas com separação Wedding/Elopement e integração Ads.",
        changes: [
            "Nova aba 'Funil Metas' com tabela completa de métricas do funil de vendas.",
            "Toggle de 3 visões: Wedding (apenas casamentos), Elopement (apenas elopements), Total (combinado).",
            "Separação completa de dados Wedding e Elopement em todas as métricas.",
            "Integração de dados de Meta Ads e Google Ads com cards de spend, clicks e CPM (em progresso).",
            "Cálculo automático de CPL baseado no investimento total e leads gerados.",
            "Cards de taxas de conversão (CVR) entre cada etapa do funil.",
            "Comparação com período anterior e metas planejadas.",
            "Modal de drill-down para visualizar deals de cada etapa.",
            "Nova logo Welcome Weddings no header do dashboard.",
        ],
    },
    {
        version: "1.5.0",
        date: "02/03/2026",
        description: "Refinamento SDR: Funil Semanal e métricas sincronizadas.",
        changes: [
            "Funil SDR agora exibe a última semana completa por padrão.",
            "Sincronização total entre cards de KPI e baldes do gráfico (início no domingo).",
            "Incorporação de novos campos: Fonte do Lead, Qualificação SQL e Status de Taxa.",
            "Anotação de picos históricos (Ago/24 e Jan/25) no gráfico de taxa de serviço.",
            "Aumento da janela histórica de deals SDR para 180 dias.",
        ],
    },
    {
        version: "1.4.0",
        date: "27/02/2026",
        description: "Correção da Lógica de Casamentos Ganhos e Pipeline Closer.",
        changes: [
            "Alteração do ID do pipeline Closer de 8 para 3.",
            "Correção da inversão de status (Ganho vs Aberto) no script de sincronização.",
            "Implementação da regra global de identificação de ganho via campo '[WW] [Closer] Data-Hora Ganho'.",
            "Mapeamento direto do campo customizado 87 para persistência de data de fechamento.",
            "Recarga total de 22.000+ deals para garantir integridade histórica.",
        ],
    },
    {
        version: "1.3.0",
        date: "27/02/2026",
        description: "Revamp estrutural Aba SDR (Topo do Funil).",
        changes: [
            "Renomeação oficial da tab para 'SDR'.",
            "Módulo 2.1: Cards de KPI otimizados com MM4 visível, no-show rate e qualificação com ruleset de alertas.",
            "Módulo 2.2: Novo gráfico Híbrido exibindo Leads vs Engajados + Curva de Qualificação.",
            "Módulo 2.3: Funil visual de 5 etapas com lógica estrita de pass-through.",
            "Módulo 2.4: Painéis duplo de Motivos de Perda (Global vs Últimos 4 Meses com detecção de tendências).",
            "Módulo 2.5: Acompanhamento mensal isolado de rejeição por Taxa de Serviço.",
        ],
    },
    {
        version: "1.2.0",
        date: "26/02/2026",
        description: "Dicionário de Métricas e Auxiliares Visuais.",
        changes: [
            "Criação da página 'Dicionário' com definições detalhadas de cada métrica.",
            "Implementação de hover helpers (tooltips) em todos os KPIs e títulos de seção.",
            "Centralização das regras de cálculo e origens de dados em `metrics-definitions.ts`.",
            "Melhoria na transparência dos dados para os usuários finais.",
        ],
    },
    {
        version: "1.1.0",
        date: "25/02/2026",
        description: "Migração de infraestrutura de dados e sistema de versionamento.",
        changes: [
            "Migração da origem de dados: API do ActiveCampaign -> Supabase Database.",
            "Eliminação de problemas de CORS e dependência de proxy server-side.",
            "Implementação de sistema de versionamento e log de alterações (este log).",
            "Mapeamento automático de campos personalizados do DB para o dashboard.",
            "Melhoria na performance de carregamento inicial.",
        ],
    },
    {
        version: "1.0.0",
        date: "19/02/2026",
        description: "Lançamento inicial do Dashboard de Vendas Welcome Weddings.",
        changes: [
            "Visualização de KPIs (SDR Volume, Taxa de Qualificação, Conversão Closer).",
            "Gráficos de tendência semanal e mensal (Area e Bar charts).",
            "Análise de motivos de perda e pipeline por idade/estágio.",
            "Tema escuro personalizado (Berry/Gold/Surface).",
            "Consumo direto da API ActiveCampaign via Proxy Next.js.",
        ],
    },
];

export const CURRENT_VERSION = VERSION_HISTORY[0];
